MvcProjeKampi2/Controllers/HeadingController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi2.Controllers
{
    public class HeadingController : Controller
    {
        HeadingManager _headingManager = new HeadingManager(new EfHeadingDal());
        CategoryManager _categoryManager = new CategoryManager(new EfCategoryDal());
        AuthorManager _authorManager = new AuthorManager(new EfAuthorDal());


        public ActionResult HeadingList()
        {
            var values = _headingManager.GetList();
            return View(values);
        }

        [HttpGet]
        public ActionResult AddHeading()
        {
            List<SelectListItem> categoryValues = (from x in _categoryManager.GetList()
                                                   select new SelectListItem
                                                   {
                                                       Text = x.CategoryName,
                                                       Value = x.CategoryId.ToString()
                                                   }
                                                  ).ToList();


            List<SelectListItem> authorValues = (from x in _authorManager.GetList()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.AuthorName + " " + x.AuthorSurname,
                                                     Value = x.AuthorId.ToString()
                                                 }
                                                 ).ToList();
            ViewBag.vCategories = categoryValues;
            ViewBag.vAuthors = authorValues;

            return View();
        }

        [HttpPost]
        public ActionResult AddHeading(Heading heading)
        {
            heading.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            _headingManager.HeadingAdd(heading);
            return RedirectToAction("HeadingList");
        }


        [HttpGet]
        public ActionResult EditHeading(int id)
        {
            List<SelectListItem> categoryValues = (from x in _categoryManager.GetList()
                                                   select new SelectListItem
                                                   {
                                                       Text = x.CategoryName,
                                                       Value = x.CategoryId.ToString()
                                                   }
                                                 ).ToList();


            List<SelectListItem> authorValues = (from x in _authorManager.GetList()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.AuthorName + " " + x.AuthorSurname,
                                                     Value = x.AuthorId.ToString()
                                                 }
                                                 ).ToList();
            ViewBag.vCategories = categoryValues;
            ViewBag.vAuthors = authorValues;

            var values = _headingManager.GetByID(id);
            return View(values);
        }

        [HttpPost]
        public ActionResult EditHeading(Heading heading)
        {
            heading.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            _headingManager.HeadingUpdate(heading);
            return RedirectToAction("HeadingList");
        }

        public ActionResult DeleteHeading(int id)
        {
            var values = _headingManager.GetByID(id);
            values.HeadingStatus = false;
            _headingManager.HeadingUpdate(values);
            return RedirectToAction("HeadingList");
        }

        public ActionResult CorrectHeading(int id)
        {
            var values = _headingManager.GetByID(id);
            values.HeadingStatus = true;
            _headingManager.HeadingUpdate(values);
            return RedirectToAction("HeadingList");
        }

    }
}

MvcProjeKampi2/Views/Heading/AddHeading.cshtml
@model EntityLayer.Concrete.Heading

@{
    ViewBag.Title = "AddHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
{
    <label>Başlık Adı</label>
    <input type="text" name="HeadingName" class="form-control" />
    @Html.ValidationMessageFor(x => x.HeadingName)

    <br />
    <br />

    <label>Kategori</label>
    @Html.DropDownListFor(m => m.CategoryId, (List<SelectListItem>)ViewBag.vCategories, new { @class = "form-control" })

    <br />
    <br />

    <label>Yazar</label>
    @Html.DropDownListFor(m => m.AuthorId, (List<SelectListItem>)ViewBag.vAuthors, new { @class = "form-control" })

    <br />
    <br />

    <button class="btn btn-info">Kaydet</button>
}

MvcProjeKampi2/Views/Heading/EditHeading.cshtml
@model EntityLayer.Concrete.Heading

@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<style>
    .field-validation-error {
        color: red;
        font-weight: bold;
    }
</style>


@using (Html.BeginForm("EditHeading", "Heading", FormMethod.Post))
{
    @Html.HiddenFor(x => x.HeadingId)

    <label>Başlık Adı</label>
    @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.HeadingName)

    <br />
    <br />

    <label>Kategori</label>
    @Html.DropDownListFor(m => m.CategoryId, (List<SelectListItem>)ViewBag.vCategories, new { @class = "form-control" })

    <br />
    <br />

    <label>Yazar</label>
    @Html.DropDownListFor(m => m.AuthorId, (List<SelectListItem>)ViewBag.vAuthors, new { @class = "form-control" })

    <br />
    <br />

    <button class="btn btn-info">Güncelle</button>
}

MvcProjeKampi2/Views/Heading/HeadingList.cshtml
@model List<EntityLayer.Concrete.Heading>

@{
    ViewBag.Title = "HeadingList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    string badgeStyle;
}

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Başlık İşlemleri</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 20%">
                                Oluşturan Yazar
                            </th>
                            <th style="width: 20%">
                                Durum
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {

                            switch (item.CategoryId)
                            {
                                case 2: badgeStyle = "badge-primary"; break;
                                case 3: badgeStyle = "badge-warning"; break;
                                case 4: badgeStyle = "badge-success"; break;
                                case 5: badgeStyle = "badge-info"; break;
                                case 6: badgeStyle = "badge-warning"; break;
                                case 10: badgeStyle = "badge-primary"; break;
                                case 12: badgeStyle = "badge-danger"; break;
                                default: badgeStyle = "badge-secondary"; break;
                            }


                            <tr>
                                <td>
                                    @item.HeadingId
                                </td>
                                <td>
                                    <a>
                                        @item.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @item.HeadingDate.ToString("dd-MMM-yyy")
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Author.AuthorImage">
                                            <a>
                                                @item.Author.AuthorName  @item.Author.AuthorSurname
                                            </a>
                                        </li>
                                    </ul>
                                </td>

                                @if (item.HeadingStatus == true)
                                {
                                    <td>
                                        <span class="badge badge-info">@item.HeadingStatus</span>
                                    </td>
                                }
                                else
                                {
                                    <td>
                                        <span class="badge badge-danger">@item.HeadingStatus</span>
                                    </td>
                                }


                                <td class="project-state">
                                    <span class="badge @badgeStyle">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingId">
                                        <i class="fas fa-folder">
                                        </i>
                                        Yazılar
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/Heading/EditHeading/@item.HeadingId">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    @if (item.HeadingStatus == true)
                                    {
                                        <a class="btn btn-danger btn-sm" href="/Heading/DeleteHeading/@item.HeadingId">
                                            <i class="fas fa-trash"></i>
                                            Sil
                                        </a>
                                    }
                                    else
                                    {
                                        <a class="btn btn-info btn-sm" href="/Heading/CorrectHeading/@item.HeadingId">
                                            <i class="fas fa-plus-circle"></i>
                                            Ekle
                                        </a>
                                    }

                                </td>
                                </tr>
                            }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
</body>
</html>

<a href="/Heading/AddHeading/" class="btn btn-outline-warning">Başlık Ekle</a>





@*<div class="container">
        <table class="table table-hover">
            <br />
            <br />

            <tr>
                <th>#</th>
                <th>Ad</th>
                <th>Tarih</th>
                <th>Sil</th>
                <th>Güncelle</th>
                <th>Başlıklar</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <th>@item.HeadingId</th>
                    <td>@item.HeadingName</td>
                    <td>@item.HeadingDate</td>
                    <td>@item.Category.CategoryName</td>
                    <td>@item.Author.AuthorName @item.Author.AuthorSurname</td>
                    <td><a href="/AdminCategory/DeleteCategory/@item.CategoryId" class="btn btn-danger">Sil</a></td>
                    <td><a href="/AdminCategory/EditCategory/@item.CategoryId" class="btn btn-warning">Güncelle</a></td>
                    <td><a href="#" class="btn btn-info">Başlıklar</a></td>
                </tr>
            }
        </table>
        <a href="/Heading/AddHeading/" class="btn btn-outline-warning">Yeni Başlık Ekle</a>
    </div>*@