MvcProjeKampi2/Controllers/ContactController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi2.Controllers
{
    public class ContactController : Controller
    {
        ContactManager _contactManager = new ContactManager(new EfContactDal());
        MessageManager _messageManager = new MessageManager(new EfMessageDal());

        public ActionResult Index()
        {
            var values = _contactManager.GetList();
            return View(values);
        }

        public ActionResult ContactDetail(int id)
        {
            var values = _contactManager.GetByID(id);
            return View(values);
        }




        public PartialViewResult MessageLeftPartial()
        {

            ViewBag.inboxCount = _messageManager.GetListInBox().Count();
            ViewBag.sendCount = _messageManager.GetListSendBox().Count();
            ViewBag.messagesCount = _messageManager.GetListSendBox().Count() + _messageManager.GetListInBox().Count();
            return PartialView();
        }
    }
}

MvcProjeKampi2/Controllers/MessageController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Security.Application;
using BusinessLayer.ValidationRules;
using FluentValidation.Results;
using System.EnterpriseServices;


namespace MvcProjeKampi2.Controllers
{
    public class MessageController : Controller
    {
        MessageManager _messageManager = new MessageManager(new EfMessageDal());
        MessageValidator _messageValidator = new MessageValidator();
        public ActionResult InBox()
        {
            var values = _messageManager.GetListInBox();
            ViewBag.inboxCount = values.Count();
            return View(values);
        }

        public ActionResult SendBox()
        {
            var values = _messageManager.GetListSendBox();
            ViewBag.sendboxCount = values.Count();
            return View(values);
        }


        public ActionResult GetInBoxMessageDetails(int id)
        {
            var values = _messageManager.GetByID(id);
            return View(values);
        }

        public ActionResult GetSendBoxMessageDetails(int id)
        {
            var values = _messageManager.GetByID(id);
            return View(values);
        }


        [HttpGet]
        public ActionResult NewMessage()
        {
            var values = _messageManager.GetListInBox().FirstOrDefault();
            values.SenderMail = "";
            values.ReceiverMail = "";
            values.MessageContent = "";
            values.Subject = "";
            return View(values);
        }

        [HttpPost]
        public ActionResult NewMessage(Message message)
        {
            ValidationResult result = _messageValidator.Validate(message);

            if (result.IsValid)
            {
                // Kullanıcının girdiği HTML içeriği sanitize ediliyor
                message.MessageContent = Sanitizer.GetSafeHtmlFragment(message.MessageContent);

                // Mesajın diğer bilgileri dolduruluyor
                message.MessageDate = DateTime.Now;
                message.SenderMail = "admin@gmail.com"; // Gönderen sabit bir admin e-postası

                // Veritabanına kaydediliyor
                _messageManager.MessageAdd(message);

                return RedirectToAction("SendBox");

            }

            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }

            return View(message);

        }

    }
}

MvcProjeKampi2/Views/Message/GetInBoxMessageDetails.cshtml
@model EntityLayer.Concrete.Message

@{
    ViewBag.Title = "GetInBoxMessageDetails";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Compose</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Compose</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">

                @Html.Action("MessageLeftPartial", "Contact")

                <!-- /.col -->
                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Read Mail</h3>
                            <div class="card-tools">
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <div class="mailbox-read-info">
                                <h5>Konu @Html.DisplayFor(x => x.Subject)</h5>
                                <h6>
                                    Kimden: @Html.DisplayFor(x => x.SenderMail)
                                    <span class="mailbox-read-time float-right">
                                        <small>
                                            @DateTime.Parse(Html.DisplayFor(x => x.MessageDate).ToString()).ToShortDateString()
                                        </small>
                                    </span>
                                </h6>
                            </div>
                            <!-- /.mailbox-read-info -->
                            <!-- /.mailbox-controls -->
                            <div class="mailbox-read-message">
                                <p>Merhaba!</p>
                                <p>
                                    @Html.DisplayFor(x => x.MessageContent)
                                </p>
                                <p>Teşekkürler,<br> @Html.DisplayFor(x => x.ReceiverMail)</p>
                            </div>
                            <!-- /.mailbox-read-message -->
                        </div>
                        <!-- /.card-footer -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
    </section>
</body>
</html>

MvcProjeKampi2/Views/Message/GetSendBoxMessageDetails.cshtml
@model EntityLayer.Concrete.Message

@{
    ViewBag.Title = "GetSendBoxMessageDetails";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Compose</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Compose</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">

                @Html.Action("MessageLeftPartial", "Contact")

                <!-- /.col -->
                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Read Mail</h3>
                            <div class="card-tools">
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <div class="mailbox-read-info">
                                <h5>Konu @Html.DisplayFor(x => x.Subject)</h5>
                                <h6>
                                    Kimden: @Html.DisplayFor(x => x.SenderMail)
                                    <span class="mailbox-read-time float-right">
                                        <small>
                                            @DateTime.Parse(Html.DisplayFor(x => x.MessageDate).ToString()).ToShortDateString()
                                        </small>
                                    </span>
                                </h6>
                            </div>
                            <!-- /.mailbox-read-info -->
                            <!-- /.mailbox-controls -->
                            <div class="mailbox-read-message">
                                <p>Merhaba!</p>
                                <p>
                                    @Html.DisplayFor(x => x.MessageContent)
                                </p>
                                <p>Teşekkürler,<br> @Html.DisplayFor(x => x.ReceiverMail)</p>
                            </div>
                            <!-- /.mailbox-read-message -->
                        </div>
                        <!-- /.card-footer -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
    </section>
</body>
</html>

MvcProjeKampi2/Views/Message/InBox.cshtml
@model List<EntityLayer.Concrete.Message>

@{
    ViewBag.Title = "InBox";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mesaj Sayfası</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">

            @Html.Action("MessageLeftPartial", "Contact")

            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Gelen Mesajlar</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Mail Kutusunda Ara">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>

                                    @foreach (var item in Model)
                                    {

                                        <tr>
                                            <td>
                                                <div class="icheck-primary">
                                                    <input type="checkbox" value="" id="check1">
                                                    <label for="check1"></label>
                                                </div>
                                            </td>
                                            <td class="mailbox-star"><a href="/Message/GetInBoxMessageDetails/@item.MessageId"><i class="fas fa-star text-warning"></i></a></td>
                                            <td class="mailbox-name"><a href="/Message/GetInBoxMessageDetails/@item.MessageId"> <b> Kime:</b>@item.ReceiverMail <i> <b>Kimden:</b>@item.SenderMail</i> </a></td>
                                            <td class="mailbox-subject" href="/Message/GetInBoxMessageDetails/@item.MessageId">
                                                <b>(@item.Subject)</b>@item.MessageContent.Substring(0, 30)...
                                            </td>
                                            <td class="mailbox-attachment"></td>
                                            <td class="mailbox-date">
                                                @item.MessageDate.ToString("dd-MMM-yy")
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

</body>
</html>

MvcProjeKampi2/Views/Message/NewMessage.cshtml
@model EntityLayer.Concrete.Message



@{
    ViewBag.Title = "NewMessage";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Compose Message</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">
    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Yeni Mesaj Sayfası</h1>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                @Html.Action("MessageLeftPartial", "Contact")
                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Yeni Mesaj Oluştur</h3>
                        </div>
                        <div class="card-body">
                            @using (Html.BeginForm("NewMessage", "Message", FormMethod.Post))
                            {
                                <div class="form-group">
                                    <input class="form-control" name="ReceiverMail" placeholder="Alıcı:" value="@Model.ReceiverMail" />
                                    @Html.ValidationMessageFor(x => x.ReceiverMail, null, new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <input class="form-control" name="Subject" placeholder="Konu:" value="@Model.Subject" />
                                    @Html.ValidationMessageFor(x => x.Subject, null, new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <textarea id="compose-textarea" name="MessageContent" class="form-control" style="height: 300px">@Model.MessageContent</textarea>
                                    @Html.ValidationMessageFor(x => x.MessageContent, null, new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <div class="btn btn-default btn-file">
                                        <i class="fas fa-paperclip"></i> Dosya Ekle
                                        <input type="file" name="attachment" />
                                    </div>
                                    <p class="help-block">Max. 32MB</p>
                                </div>
                                <div class="card-footer">
                                    <div class="float-right">
                                        <button type="button" class="btn btn-default"><i class="fas fa-pencil-alt"></i> Taslaklara Kaydet</button>
                                        <button type="submit" class="btn btn-primary"><i class="far fa-envelope"></i> Gönder</button>
                                    </div>
                                    <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> İptal Et</button>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>
    <script>
        $(function () {
            $('#compose-textarea').summernote({
                height: 300,
                toolbar: [
                    ['style', ['bold', 'italic', 'underline', 'clear']],
                    ['font', ['strikethrough', 'superscript', 'subscript']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['height', ['height']]
                ]
            });
        });
    </script>
</body>
</html>